### ISSUE TITLE
1.21 Bug Crashes When Creating a New World/ Crashes When Activating Tin Block Beacon

### ISSUE THREAD

**Issue by makumaku1974** [Khazoda/bronze#9] opened 2024-07-28 04:51 UTC
I can't seem to reproduce the problem or what it was causing but the problem is that it crashes creating a new world. When I replaced it with the previous version it works normally.

**Comment by Khazoda** [comment] 2024-07-29 13:59
Could you please provide:
- the version of Bronze that doesn't crash
- the version of Bronze that you experience a crash with

Does this occur when bronze is the only mod installed? If it only occurs with other mods installed, could you please give me a rough list of them?

**Comment by Khazoda** [comment] 2024-07-29 14:07
Also post your crashlog please if you're able to

**Comment by makumaku1974** [comment] 2024-07-30 06:58
I renamed it because testing your latest 1.0.8 crashed the game when activating the beacon with Tin Blocks https://mclo.gs/S6qtqvB

**Comment by makumaku1974** [comment] 2024-07-30 06:59
> Could you please provide:
> 
> * the version of Bronze that doesn't crash
> * the version of Bronze that you experience a crash with
> 
> Does this occur when bronze is the only mod installed? If it only occurs with other mods installed, could you please give me a rough list of them?

this is a 1.0.7 issue but the problem was with Artifacts 1.21.

**Comment by Khazoda** [comment] 2024-07-30 13:31
I've looked through the crashlog and it looks like a jade plugin is causing your crash:
`Cannot invoke "sypztep.crital.common.data.CritalItemDataEntry.baseCritChance()" because "itemData" is null`

There are however a lot of Bronze recipe loading errors, which I have now fixed in ce030ca (thank you).

I tested beacons with tin blocks and bronze blocks as bases and am able to activate them without issue. I don't know how that could be causing a crash as the only thing added is 2 JSON files for beacon base blocks and payment items.

Does your crash occur when right clicking a beacon to open the GUI, or when actually activating it with an ingot/gem?

**Comment by makumaku1974** [comment] 2024-07-30 23:07
> I've looked through the crashlog and it looks like a jade plugin is causing your crash: `Cannot invoke "sypztep.crital.common.data.CritalItemDataEntry.baseCritChance()" because "itemData" is null`
> 
> There are however a lot of Bronze recipe loading errors, which I have now fixed in [ce030ca](https://github.com/Khazoda/bronze/commit/ce030ca45e357d0db950c04bf42cebb7928d103c) (thank you).
> 
> I tested beacons with tin blocks and bronze blocks as bases and am able to activate them without issue. I don't know how that could be causing a crash as the only thing added is 2 JSON files for beacon base blocks and payment items.
> 
> Does your crash occur when right clicking a beacon to open the GUI, or when actually activating it with an ingot/gem?

ive fixed the item data issue but since the mod author deleted his github for unknown reason and could not maybe update this mod. 

Btw the crash from the beacon only happened once and it did not happen again.

**Comment by Khazoda** [comment] 2024-07-31 09:09
hmm strange. Thanks for the reports anyway, please open another issue if you get any crashes in future caused by Bronze.

**Closed by Khazoda** 2024-07-31 09:09 UTC
Labels: bug
